name: 'Get and Cache dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite' # Mention which type of actions we are creating
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash # While creating the custom actions we have to mention that which shell we have to use for executing the steps
